# Generated by Django 5.2.13 on 2026-04-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, help_text='WhatsApp phone number (e.g. +919876543210)', max_length=30, unique=True)),
                ('state', models.CharField(choices=[('idle', 'Idle — waiting for menu selection'), ('awaiting_issue', 'Awaiting issue description (Book Service)'), ('awaiting_serial', 'Awaiting serial number (Check Warranty)'), ('awaiting_job_id', 'Awaiting Job ID (Track Request)')], default='idle', max_length=30)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Temporary data for the current flow (e.g. partial form data)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversation State',
                'verbose_name_plural': 'Conversation States',
            },
        ),
    ]
