# Generated by Django 5.2.13 on 2026-04-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationstate',
            name='state',
            field=models.CharField(choices=[('idle', 'Idle — waiting for menu selection'), ('awaiting_category', 'Awaiting appliance category (Book Service)'), ('awaiting_issue', 'Awaiting issue description (Book Service)'), ('awaiting_serial', 'Awaiting serial number (Check Warranty)'), ('awaiting_auto_book', 'Awaiting YES/NO to auto-book after warranty'), ('awaiting_job_id', 'Awaiting Job ID (Track Request)')], default='idle', max_length=30),
        ),
    ]
