# Generated by Django 5.2.13 on 2026-04-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_alter_conversationstate_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationstate',
            name='state',
            field=models.CharField(choices=[('idle', 'Idle — waiting for menu selection'), ('awaiting_category', 'Awaiting appliance category (Book Service)'), ('awaiting_issue', 'Awaiting issue description (Book Service)'), ('awaiting_serial', 'Awaiting serial number (Check Warranty)'), ('awaiting_auto_book', 'Awaiting YES/NO to auto-book after warranty'), ('awaiting_job_id', 'Awaiting Job ID (Track Request)'), ('tech_awaiting_response', 'Technician awaiting ACCEPT/REJECT'), ('tech_awaiting_otp', 'Technician awaiting OTP to complete job'), ('customer_awaiting_feedback', 'Customer awaiting rating feedback'), ('customer_awaiting_comment', 'Customer awaiting feedback comment')], default='idle', max_length=40),
        ),
    ]
