# Generated by Django 5.2.13 on 2026-04-29 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('purchase_date', models.DateField()),
                ('expiry_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Warranties',
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='job_id',
            field=models.CharField(db_index=True, default='JOB-LEGACY-0000', editable=False, help_text='Auto-generated ID in format JOB-YYYYMMDD-XXXX', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='jobs_job_status_7d017a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['-created_at'], name='jobs_job_created_77460a_idx'),
        ),
        migrations.AddField(
            model_name='warranty',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to=settings.AUTH_USER_MODEL),
        ),
    ]
