# Generated by Django 5.2.13 on 2026-04-29 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_initial'),
        ('jobs', '0003_warranty_job_job_id_job_jobs_job_status_7d017a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned to Agent'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('subject', models.CharField(blank=True, default='General Inquiry', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['support', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_conversations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, help_text='Job this conversation is about (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('agent', 'Support Agent'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='jobs.conversationsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('reassigned', 'Reassigned')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='', help_text='Reason provided by technician for rejecting')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the technician accepted or rejected', null=True)),
                ('deadline', models.DateTimeField(blank=True, help_text='30 minutes from assignment — auto-expire if no response', null=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Support team member who made this assignment', limit_choices_to={'role__in': ['support', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='jobs.job')),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'technician'}, on_delete=django.db.models.deletion.CASCADE, related_name='job_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('reason', models.TextField(help_text='Reason for reporting the technician')),
                ('action_taken', models.TextField(blank=True, default='', help_text='What action was taken (e.g. warning, suspension)')),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback', models.ForeignKey(blank=True, help_text='The customer feedback that triggered this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_reports', to='feedback.feedback')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_reports', to='jobs.job')),
                ('reported_by', models.ForeignKey(limit_choices_to={'role__in': ['support', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'technician'}, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['status'], name='jobs_conver_status_3fe444_idx'),
        ),
        migrations.AddIndex(
            model_name='jobassignment',
            index=models.Index(fields=['status'], name='jobs_jobass_status_766ec1_idx'),
        ),
        migrations.AddIndex(
            model_name='jobassignment',
            index=models.Index(fields=['-assigned_at'], name='jobs_jobass_assigne_a3460e_idx'),
        ),
        migrations.AddIndex(
            model_name='jobassignment',
            index=models.Index(fields=['deadline'], name='jobs_jobass_deadlin_1a683f_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianreport',
            index=models.Index(fields=['severity'], name='jobs_techni_severit_4551f7_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianreport',
            index=models.Index(fields=['is_resolved'], name='jobs_techni_is_reso_3fd425_idx'),
        ),
    ]
