# Generated by Django 5.2.13 on 2026-04-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_conversationsession_chatmessage_jobassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the job was actually completed (OTP verified)', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='completion_otp',
            field=models.CharField(blank=True, default='', help_text='OTP sent to customer for job completion verification', max_length=6),
        ),
    ]
