# Generated by Django 5.2.13 on 2026-04-29 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('technician', 'Technician'), ('support', 'Support Team'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(blank=True, default='', help_text='Comma-separated skills (e.g. AC Repair, Plumbing, Electrical)')),
                ('availability', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='available', max_length=20)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Auto-calculated from feedback', max_digits=3)),
                ('total_jobs_completed', models.PositiveIntegerField(default=0)),
                ('total_jobs_rejected', models.PositiveIntegerField(default=0)),
                ('report_count', models.PositiveIntegerField(default=0, help_text='Number of times reported by support team')),
                ('extra_fields', models.JSONField(blank=True, default=dict, help_text='Custom columns added by support team (key-value pairs)')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes by support team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'technician'}, on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-average_rating'],
                'indexes': [models.Index(fields=['availability'], name='users_techn_availab_cbdfaf_idx')],
            },
        ),
    ]
